#!/usr/bin/python3
"""
Base Module For Air BnB Console
"""
import uuid
from datetime import datetime


class BaseModel:
    """
    Base Class of AirBnb Console
    """
    def __init__(self):
        """
        Init of Object
            Attributes:
                id(string) Random Generated by 'uuid4:(method Randome)'
                Created_at(str):Auto Generated
                    by datetime module now(get current time)
                Updated_at(str):Auto Generated by datetime and
                    generated again when object modified
                    by adding it to method that change object like save
        """
        self.id = str(uuid.uuid4())
        self.created_at = datetime.now()
        self.updated_at = datetime.now()

    def __str__(self):
        return ("[{}] ({}) {})".format(
                                    __class__.__name__,
                                    self.id,
                                    self.__dict__))

    def save(self):
        """
            for now just update update_at
        """
        self.updated_at = datetime.now()

    def to_dict(self):
        """
            convert  self dict and other public instance
                Return: Dictionary
        """
        dic = dict(self.__dict__)
        dic['__class__'] = self.__class__.__name__
        dic['updated_at'] = self.updated_at.strftime("%Y-%m-%dT%H:%M:%S.%f")
        dic['created_at'] = self.created_at.strftime("%Y-%m-%dT%H:%M:%S.%f")

        return dic
